[package]
name = "day_07"
version = "0.1.0"
edition = "2021"

[dependencies]
divan = "0.1.16"
eyre = "0.6.12"
rayon = "1.10.0"

[[bench]]
name = "day-07-bench"
path = "benches/bench.rs"
harness = false
