[package]
name = "day_03"
version = "0.1.0"
edition = "2021"

[dependencies]
divan = "0.1.17"
eyre = "0.6.12"
regex = "1.11.1"

[[bench]]
name = "day-03-bench"
path = "benches/bench.rs"
harness = false