[package]
name = "day_13"
version = "0.1.0"
edition = "2021"

[dependencies]
divan = "0.1.16"
eyre = "0.6.12"
itertools = "0.13.0"
regex = "1.11.1"

[[bench]]
name = "day-13-bench"
path = "benches/bench.rs"
harness = false
