[package]
name = "day_06"
version = "0.1.0"
edition = "2021"

[dependencies]
divan = "0.1.16"
eyre = "0.6.12"
itertools = "0.13.0"
rayon = "1.10.0"

[[bench]]
name = "day-06-bench"
path = "benches/bench.rs"
harness = false
